num1 = float(input("Введите первое число: "))
num2 = float(input("Введите второе число: "))
sum_result = num1 + num2
diff_result = num1 - num2
mul_result = num1 * num2
div_result = num1 / num2
mod_result = num1 % num2
floor_div_result = num1 // num2
print(f"{num1} + {num2} = {sum_result}")
print(f"{num1} - {num2} = {diff_result}")
print(f"{num1} * {num2} = {mul_result}")
print(f"{num1} / {num2} = {div_result}")
print(f"{num1} % {num2} = {mod_result}")
print(f"{num1} // {num2} = {floor_div_result}")