
print('''Пользователь ебет в рот этот синтаксиз и с пятой подсказки вспоминает про ебучие кавычки, введите цифры и нажмите энтер''')
biba: int = input()
boba: int = input()
x: float = float(biba)
y: float = float(boba)
print(f'''{x} + {y} = {x + y}''')
print(f'''{x} - {y} = {x - y}''')
print(f'''{x} * {y} = {x * y}''')
print(f'''{x} / {y} = {x / y}''')
print(f'''{x} % {y} = {x % y}''')
print(f'''{x} ** {y} = {x ** y}''')
print(f'''{x} // {y} = {x // y}''')
